name: Build

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/basic_setup
            - name: Build
              run: npm run build
