name: Tests

on:
    pull_request:

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/basic_setup
            - name: Unit Tests
              run: npm run test:unit
    integration-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/basic_setup
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: '21'
            - name: Cache Firebase emulator JARs
              uses: actions/cache@v4
              with:
                  path: ~/.cache/firebase/emulators
                  key: firebase-emulators-${{ hashFiles('package-lock.json') }}
            - name: Download Firebase emulators
              run: npx firebase setup:emulators:firestore
            - name: Integration Tests
              run: npm run test:integration
